name: 'aatt_snowflake_demo'
version: '1.0.0'
config-version: 2

profile: 'aatt_snowflake_connection'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
target-path: 'target'
clean-targets: ['target']

models:
  age_coe_dbt:
    +materialized: table
    staging:
      +materialized: view
