SELECT RESULT_TIME, TYPE, NAME, METHOD,AGE_GATE,SUBJECT_AGE,VERIFICATION_STATUS,REPORTED_AGE,VERIFICATION_TIME,
  DATE_PART('hour', VERIFICATION_TIME) * 3600
  + DATE_PART('minute', VERIFICATION_TIME) * 60
  + DATE_PART('second', VERIFICATION_TIME) AS TIME_IN_SECONDS
FROM {{ ref('all_eligible_results') }}
WHERE AGE_GATE = 13 OR AGE_GATE = 0